import {sealGift,readEnvelope,openGift,compactImage} from './portable.js';
import QRCode from './vendor/qr.js';
import {escape as e,cardHTML,mountExperience} from './renderers.js';
import { choices,styling,mechanism } from './personalization.js';
const main=document.querySelector('#main'),dialog=document.querySelector('#dialog');
let config,catalogue=[],me=null,draft=null,experience=null,previewFinal=false,filter='all',search='';
const base=new URL('.',import.meta.url).pathname;
const route=new URLSearchParams(location.search).get('view')||'/';
function routeUrl(view){return location.origin+base+(view==='/'?'':'?view='+encodeURIComponent(view));}
// Keep all internal routes inside the static subdirectory, including opening links in a new tab.
const internal=/^\/(?:$|templates$|my-reveals$|create\/|help$|privacy$|terms$|report$|unlock$|restore$)/;
new MutationObserver(()=>{for(const a of document.querySelectorAll('a[href]')){const href=a.getAttribute('href');if(internal.test(href))a.href=routeUrl(href);}}).observe(document.documentElement,{childList:true,subtree:true});
document.addEventListener('click',event=>{if(event.target.closest?.('a.skip')){event.preventDefault();document.querySelector('#main').focus();document.querySelector('#main').scrollIntoView();}});
let giftEnvelope;

const draftKey='sr.web.draft.v1';
async function api(path){
 if(path==='/api/config')return{development:false,staticEdition:true,policy:{paidCap:20,freeCap:20,months:0}};
 if(path==='/api/catalogue'){const response=await fetch(new URL('./catalogue.json',import.meta.url));if(!response.ok)throw Error('Reconnect and reload the studio.');return response.json();}
 if(path==='/api/me')return{paid:true};
 if(path.startsWith('/api/r/')){if(!catalogue.length)catalogue=await api('/api/catalogue');if(!giftEnvelope){const token=new URLSearchParams(location.hash.slice(1)).get('gift');if(!token)throw Error('Missing reveal link.');giftEnvelope=readEnvelope(token,catalogue);}if(path.endsWith('/cover'))return giftEnvelope.cover;const c=await openGift(giftEnvelope,catalogue);return path.endsWith('/clues')?{clues:c.clues}:c;}
 throw Error('This operation is unavailable in the browser edition.');
}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');setTimeout(()=>el.classList.remove('visible'),5000);}
function sample(t){return {...styling(),revealStyle:t.supports_clues?'design':'slider',celebration:t.occasions.includes('birthday')?'confetti':'none',templateId:t.id,cover:t.cover_copy,headline:t.example_final_headline,body:t.occasions.includes('work')?'Thank you for a thoughtful and enjoyable collaboration. We wanted to mark it with something nice.':'Some time together, a little adventure, and something lovely to look forward to.',note:'I’ll send the details separately.',recipient:'Alex',sender:t.occasions.includes('work')?'Example Studio':'Jamie',signoff:t.occasions.includes('work')?'From':'With love, from',number:t.id==='big-number'?'30':'',clues:t.supports_clues?['Clear a little space in your diary.','Something lovely is closer than you think.','The details are just one click away.']:[],palette:'original',showCredit:t.access==='free',photo:route==='/design-lab'&&location.search.includes('case=media')&&t.supports_photo?'/sample-photo.webp':undefined,logo:route==='/design-lab'&&location.search.includes('case=media')&&t.supports_logo?'/sample-logo.webp':undefined};}
function date(value){return new Date(value).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'});}
function nav(){const recipient=route.startsWith('/r/');document.querySelector('#header').innerHTML=`<a class="brand" href="/" aria-label="Surprise Reveal home"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M3 6h26v21H3zM3 6l13 12L29 6M3 27l9-10M29 27l-9-10"/></svg><span>Surprise<span class="brand-serif">Reveal</span></span></a>${recipient?'':`<nav aria-label="Main"><a href="/templates">The collection</a><a href="/my-reveals">My reveals</a><a class="nav-create" href="/create/little-something">Make a surprise <span aria-hidden="true">↗</span></a></nav>`}`;
document.querySelector('#footer').innerHTML=recipient?'':`<span>A little digital stationery studio.</span><div><a href="/help">Help</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/FingerOfShame/">Finger Game hub ↗</a>${config.development?'<a href="/design-lab">Design lab</a>':''}</div>`;}
function devNotice(){return config.staticEdition?'<div class="dev-notice">FINGER GAME EDITION <span>Create a card. Share a little surprise. Free for now.</span></div>':'';}
async function init(){try{config=await api('/api/config');nav();
 if(route.startsWith('/r/'))return recipient();
 catalogue=await api('/api/catalogue');try{me=await api('/api/me');}catch{}
 if(route==='/design-lab'){if(!config.development)return missing();return lab();}
 if(route.startsWith('/create/'))return editor();if(route==='/my-reveals')return owners();if(['/unlock','/restore','/purchase/return'].includes(route))return shelf(false);if(['/help','/privacy','/terms','/report'].includes(route))return information();return shelf(route==='/');
 }catch(err){main.innerHTML=`<section class="empty"><h1>The studio is taking a moment.</h1><p>${e(err.message)}</p><button id="retry">Try again</button></section>`;document.querySelector('#retry').onclick=init;}}
function shelf(home){main.innerHTML=`${devNotice()}${home?`<section class="hero"><div class="hero-copy"><p class="eyebrow">THE MOMENT BEFORE THE MOMENT</p><h1>A little suspense.<br>A lovely <em>surprise.</em></h1><p class="lede">Make the surprise part of the present.</p><p>Pick a design. Add your message. Send a link.<br>A note worth opening, for any occasion.</p><div class="hero-actions"><a class="primary button" href="/create/little-something">Make a surprise <span>↗</span></a><a href="#collection">Find your design ↓</a></div><p class="small">All 12 designs. Free for now. No account needed.</p></div><div class="hero-example"><div id="hero-card"></div><p class="sample-label">A fictional little something. Go on, open it.</p></div></section>`:''}<section id="collection" class="collection"><div class="section-heading"><div><p class="eyebrow">THE STATIONERY DRAWER</p><h${home?'2':'1'}>A design for your kind of surprise.</h${home?'2':'1'}></div><p>12 designs.<br>Make it your own.</p></div><div class="filter-bar"><div class="filters" role="group" aria-label="Occasions">${[['all','All designs'],['birthday','Birthday'],['just-because','Just because'],['experience','Experiences'],['thank-you','Thank you'],['work','Work'],['seasonal','Seasonal']].map(([id,label])=>`<button data-filter="${id}" aria-pressed="${filter===id}">${label}</button>`).join('')}</div><label class="search">Find a design <input type="search" placeholder="Name or occasion" value="${e(search)}"></label></div><div id="shelf" class="shelf"></div></section><section class="offer"><p class="eyebrow">ONE COLLECTION. MANY LITTLE MOMENTS.</p><h2>For birthdays. For brilliant work.<br>For absolutely no reason.</h2><p>12 designs. Choose how your surprise opens.</p><a class="button" href="/unlock">Explore all the designs ↗</a><p class="small">Free temporary edition · no payments</p></section>`;
 if(home){const t=catalogue[0],s={...sample(t),cover:'I have a little\nsomething for you.',headline:'Saturday breakfast is on me.'};experience=mountExperience(document.querySelector('#hero-card'),t,s,async()=>s);}
 document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));tiles();});document.querySelector('.search input').oninput=ev=>{search=ev.target.value;tiles();};tiles();}
function tiles(){const matches=catalogue.filter(t=>(filter==='all'||t.occasions.includes(filter))&&`${t.name} ${t.occasions.join(' ')}`.toLowerCase().includes(search.toLowerCase()));document.querySelector('#shelf').innerHTML=matches.length?matches.map((t,i)=>`<a class="template-tile" href="/create/${t.id}" aria-label="Use ${e(t.name)}, ${t.access==='free'?'free':'Full Collection preview'}"><div class="tile-art art-${i%3}">${cardHTML(t,sample(t),false,true)}</div><div class="tile-caption"><div><h3>${e(t.name)}</h3><p>${{envelope:'Choose how it opens',scratch:'Choose how it opens',clues:'A trail of clues',curtains:'Choose how it opens'}[t.mechanism]}</p></div><span class="tier ${t.access}">${t.access==='free'?'Free':'Collection'}</span></div></a>`).join(''):'<p class="empty">No designs match. Try another occasion or name.</p>';}
function readDraft(t){try{const saved=JSON.parse(localStorage.getItem(draftKey));if(saved&&catalogue.some(x=>x.id===saved.templateId)&&['cover','headline','body'].every(k=>typeof saved[k]==='string'))return {...sample(t),...saved,templateId:t.id};}catch{}return sample(t);}
function save(){try{localStorage.setItem(draftKey,JSON.stringify(draft));document.querySelector('#saved').textContent='Saved on this device';}catch{document.querySelector('#saved').textContent='Device storage unavailable. Export a copy of your draft.';}}
function field(key,label,max,multiline=false,optional=false){return `<label class="field">${label}${optional?'<span class="optional">Optional</span>':''}${multiline?`<textarea name="${key}" maxlength="${max}" rows="${key==='body'?5:2}">${e(draft[key])}</textarea>`:`<input name="${key}" maxlength="${max}" value="${e(draft[key])}">`}<span class="field-count" data-count="${key}">${[...(draft[key]||'')].length} / ${max}</span></label>`;}
async function editor(){let t=catalogue.find(t=>t.id===route.split('/')[2]);if(!t)return missing();draft=readDraft(t);const editId=new URLSearchParams(location.search).get('edit');if(editId&&me){try{const r=await api(`/api/reveals/${editId}`);draft={...r.content,editId:r.id,expected:r.revision};t=catalogue.find(x=>x.id===draft.templateId);draft.signoff??=t.occasions.includes('work')?'From':'With love, from';}catch(err){toast(err.message);}}
 main.innerHTML=`${devNotice()}<div class="editor-heading"><a href="/templates">← The collection</a><h1>Your little surprise.</h1><p id="saved" role="status">Saved on this device</p></div><div class="editor"><form id="edit-form"><div class="form-section"><p class="eyebrow">01 / PICK YOUR PAPER</p><label class="field">Design<select name="templateId">${catalogue.map(x=>`<option value="${x.id}" ${x.id===t.id?'selected':''}>${e(x.name)}${x.access==='paid'?'':''}</option>`).join('')}</select></label><p id="premium-note" class="small"></p><label class="field">Palette<select name="palette"><option value="original">Original</option><option value="alternate" ${draft.palette==='alternate'?'selected':''}>Evening edition</option></select></label></div><div class="form-section"><p class="eyebrow">02 / THE OUTSIDE</p>${field('recipient','For',80,false,true)}${field('sender','From',80,false,true)}${field('cover','Cover message',120,true)}<p class="small">Keep the big news for the final message.</p></div><div class="form-section"><p class="eyebrow">03 / THE SURPRISE</p>${field('headline','Surprise headline',180,true)}${field('body','Your message',2000,true)}${field('note','Practical note',500,true,true)}${field('signoff','Sign-off',120,false,true)}<p class="small">Shown above your name. Write your own closing words, or leave blank for your name alone.</p><div id="extras"></div></div><div class="form-section customization"><p class="eyebrow">04 / MAKE IT YOURS</p><h2>A little more you.</h2><p class="small">Choose the look. Set the mood. Make an entrance.</p>${styleField('font','Lettering')}${styleField('backdrop','Background style')}<div id="background-upload"></div>${styleField('revealStyle','How it opens')}${styleField('celebration','The finishing touch')}<div id="scratch-settings"></div></div><div class="form-section"><button type="button" id="export">Export draft</button><label class="field">Import a saved draft<input id="import" type="file" accept="application/json"></label><p class="small">Keep gift codes, passwords and private details separate.</p></div></form><div class="preview-column"><div class="preview-toolbar"><span>THE RECIPIENT’S VIEW</span><div><button id="view-cover" aria-pressed="true">Cover</button><button id="view-final" aria-pressed="false">Final message</button></div></div><div class="preview-surface"><div id="preview"></div></div><label class="motion-control"><input id="reduce" type="checkbox"> Reduce motion</label><p class="sample-label">Your preview · the final message stays behind the reveal.</p></div></div><div class="editor-bottom"><span id="publish-note">Make a link to send to your recipient.</span><div><button id="mobile-preview">Preview</button><button id="publish" class="primary">Make a link ↗</button></div></div>`;
 const form=document.querySelector('#edit-form');
 function extra(){const t=currentTemplate();document.querySelector('#premium-note').textContent=t.access==='paid'?'Full Collection design. Preview freely; publishing needs the unlock.':'Included in this free edition.';document.querySelector('#extras').innerHTML=`${t.id==='big-number'?field('number','Milestone display',8,false,true):''}${t.supports_clues?'<label class="field">Clues, one per line<textarea name="clues" rows="4" placeholder="One to three short clues">'+e(draft.clues?.join('\n')||'')+'</textarea><span class="small">1–3 clues · up to 180 characters each</span></label>':''}${t.supports_photo?uploadField('photo'):''}${t.supports_logo?uploadField('logo'):''}`;document.querySelector('#background-upload').innerHTML=uploadField('background')+'<p class="small">Your image appears on the cover and final card. Choose artwork that keeps the surprise secret. Remove it to use the background style.</p>';document.querySelector('#scratch-settings').innerHTML=mechanism(t,draft)==='scratch'?styleField('foil','Scratch foil')+styleField('scratchTool','Scratch with')+styleField('scratchSound','Scratch audio')+'<p class="small">Sounds start muted. Your recipient can choose to turn them on.</p>':'';document.querySelectorAll('[data-upload]').forEach(el=>el.onchange=ev=>upload(ev,extra));document.querySelectorAll('[data-remove]').forEach(el=>el.onclick=()=>{delete draft.publishKey;delete draft[el.dataset.remove+'Id'];delete draft[el.dataset.remove];save();extra();preview();});}
 form.oninput=ev=>{const key=ev.target.name;if(!key||ev.target.type==='file')return;if(key==='templateId')return;delete draft.publishKey;draft[key]=key==='clues'?ev.target.value.split('\n').filter(s=>s.trim()):ev.target.value;document.querySelector(`[data-count="${key}"]`)?.replaceChildren(document.createTextNode(`${[...ev.target.value].length} / ${ev.target.maxLength}`));save();if(key==='revealStyle')extra();preview();};
 form.querySelector('[name="templateId"]').onchange=ev=>{delete draft.publishKey;draft.templateId=ev.target.value;const chosen=currentTemplate();if((draft.photoId&&!chosen.supports_photo)||(draft.logoId&&!chosen.supports_logo)||(draft.clues?.length&&!chosen.supports_clues))toast('This design hides incompatible extras. They stay in your draft for switching back; they will not be published in this design.');save();extra();preview();};
 document.querySelector('#view-cover').onclick=()=>{previewFinal=false;preview();};document.querySelector('#view-final').onclick=()=>{previewFinal=true;preview();};document.querySelector('#reduce').onchange=preview;
 document.querySelector('#export').onclick=()=>download(JSON.stringify(draft,null,2),'surprise-draft.json','application/json');
 document.querySelector('#import').onchange=async ev=>{try{const f=ev.target.files[0];if(f.size>7*1024*1024)throw new Error('Draft file is too large.');const d=JSON.parse(await f.text());if(!catalogue.some(t=>t.id===d.templateId)||typeof d.body!=='string')throw new Error('Choose a valid exported draft.');for(const k of ['cover','headline','body','sender','recipient','note','signoff','number',...Object.keys(choices)])if(d[k]!=null&&typeof d[k]!=='string')throw new Error('Invalid draft text.');draft={...sample(catalogue.find(t=>t.id===d.templateId)),...d,editId:undefined,expected:undefined};localStorage.setItem(draftKey,JSON.stringify(draft));location.href=routeUrl(`/create/${draft.templateId}`);}catch(err){toast(err.message);}};
 document.querySelector('#publish').onclick=publish;document.querySelector('#mobile-preview').onclick=recipientPreview;extra();preview();save();}
function recipientPreview(){
 const content=compatibleContent(),t=currentTemplate();
 dialog.classList.add('recipient-preview-dialog');dialog.setAttribute('aria-labelledby','recipient-preview-title');
 showDialog('<p class="eyebrow">TRY YOUR SURPRISE</p><h2 id="recipient-preview-title">Recipient preview</h2><p class="small">Open it as your recipient would. Close this preview to keep editing.</p><div id="recipient-preview"></div>');
 const trial=mountExperience(dialog.querySelector('#recipient-preview'),t,content,async()=>({...content,showCredit:!me?.paid}),{loadClues:async()=>({clues:content.clues||[]}),reduced:document.querySelector('#reduce').checked});
 dialog.addEventListener('close',()=>{trial.destroy();dialog.classList.remove('recipient-preview-dialog');dialog.removeAttribute('aria-labelledby');},{once:true});
}
function currentTemplate(){return catalogue.find(t=>t.id===draft.templateId);}
function compatibleContent(){const t=currentTemplate();return {...draft,...(!t.supports_photo?{photoId:'',photo:undefined}:{}),...(!t.supports_logo?{logoId:'',logo:undefined}:{}),...(!t.supports_clues?{clues:[]}:{}),...(t.id!=='big-number'?{number:''}:{})};}
function preview(){experience?.destroy();const t=currentTemplate(),host=document.querySelector('#preview');if(!host)return;document.querySelector('#view-cover').setAttribute('aria-pressed',!previewFinal);document.querySelector('#view-final').setAttribute('aria-pressed',previewFinal);const content=compatibleContent();if(previewFinal)host.innerHTML=cardHTML(t,content,true);else experience=mountExperience(host,t,content,async()=>({...content,showCredit:!me?.paid}),{loadClues:async()=>({clues:content.clues||[]}),reduced:document.querySelector('#reduce').checked});}
function styleField(key,label){const selected=styling(draft)[key];return `<label class="field">${label}<select name="${key}">${choices[key].map(([id,label])=>`<option value="${id}" ${selected===id?'selected':''}>${label}</option>`).join('')}</select></label>`;}
function uploadField(kind){return `<label class="field">${kind==='logo'?'Authorised logo':kind==='background'?'Upload a background image':'Optional photograph'}<input type="file" accept="image/png,image/jpeg,image/webp" data-upload="${kind}"><span class="small">By uploading you confirm permission to use it. JPEG, PNG or WebP · max 5 MB.</span></label>${draft[kind+'Id']?`<p class="small">${kind} attached <button type="button" data-remove="${kind}">Remove</button></p>`:''}`;}
async function upload(ev,refresh){const file=ev.target.files[0];if(!file)return;const kind=ev.target.dataset.upload;ev.target.disabled=true;try{const image=await compactImage(file);draft[kind]=image;draft[kind+'Id']=crypto.randomUUID();delete draft.publishKey;save();refresh?.();preview();toast('Image prepared on your device and attached.');}catch(err){toast(err.message);}finally{ev.target.disabled=false;}}

function showDialog(content){dialog.innerHTML=`<button class="dialog-close" aria-label="Close">×</button>${content}`;dialog.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.showModal();}

async function publish(){const button=document.querySelector('#publish');button.disabled=true;try{save();if(!crypto?.subtle)throw Error('Use a current browser on HTTPS to make a link.');const gift=await sealGift(compatibleContent(),catalogue);const r={id:crypto.randomUUID(),url:routeUrl('/r/gift')+'#gift='+gift.token,content:gift.content,created:new Date().toISOString()};let saved=true;try{const cards=JSON.parse(localStorage.getItem('sr.web.reveals.v1')||'[]');cards.unshift(r);localStorage.setItem('sr.web.reveals.v1',JSON.stringify(cards.slice(0,20)));}catch{saved=false;}showShare(r);if(!saved)toast('Your link is ready. Copy it now; this browser could not save it.');}catch(err){toast(err.message);}finally{button.disabled=false;}}
function showShare(r){showDialog(`<p class="eyebrow">YOUR SURPRISE IS READY</p><h2>A little moment, ready to open.</h2><p>Copy the complete link and send it to your recipient.</p><label class="field">Recipient link<input id="share-link" readonly value="${e(r.url)}"></label><div class="share-actions"><button id="copy-link" class="primary">Copy link</button><a class="button" href="${e(r.url)}" target="_blank" rel="noopener noreferrer">Open recipient view ↗</a></div><p class="small">Anyone with this link can open the card. A sent link cannot be changed or revoked. Keep passwords, gift codes and sensitive details separate. This is a temporary website.</p><div id="qr-slot"><p class="small">Preparing your QR code…</p></div><a href="/my-reveals">My saved links →</a>`);dialog.querySelector('#copy-link').onclick=()=>copyLink(r.url,dialog.querySelector('#share-link'));loadQr(r).then(data=>{if(!dialog.open||!dialog.querySelector('#qr-slot'))return;dialog.querySelector('#qr-slot').innerHTML=`<img class="qr" src="${e(data)}" alt="QR code for this surprise"><button id="print-card">Print A6 presentation card</button>`;dialog.querySelector('#print-card').onclick=()=>printCard(r);}).catch(()=>{if(dialog.querySelector('#qr-slot'))dialog.querySelector('#qr-slot').innerHTML='<p class="small">This link is too long for a QR code. Use Copy link instead.</p>';});}

async function copyLink(url,input){try{await navigator.clipboard.writeText(url);toast('Link copied.');}catch{input?.select();toast('Copy didn’t work here. Select the link and copy it.');}}
async function loadQr(r){if(!r.qrData)r.qrData=await QRCode.toDataURL(r.url,{width:410,margin:4,errorCorrectionLevel:'M'});return r.qrData;}
async function printCard(r){try{await loadQr(r);}catch{return toast('Use the complete link; this card is too large for a QR code.');}dialog.close();const sheet=document.createElement('section');sheet.id='print-sheet';sheet.innerHTML=`<div class="print-card"><p class="eyebrow">A LITTLE MOMENT, JUST FOR YOU</p><h1>A surprise<br>is waiting.</h1><p>Open your camera and scan.</p><img class="qr" src="${e(r.qrData)}" alt="Reveal QR code"><p class="small">Surprise Reveal · Finger Game</p></div>`;document.body.append(sheet);const cleanup=()=>sheet.remove();window.addEventListener('afterprint',cleanup,{once:true});requestAnimationFrame(()=>requestAnimationFrame(()=>window.print()));}
async function owners(){let cards=[];try{const data=JSON.parse(localStorage.getItem('sr.web.reveals.v1')||'[]');if(Array.isArray(data))cards=data.filter(r=>r&&typeof r.id==='string'&&typeof r.url==='string'&&r.content&&typeof r.content.headline==='string'&&r.url.startsWith(routeUrl('/r/gift')+'#gift=')).slice(0,20);}catch{}main.innerHTML=`${devNotice()}<section class="owner-section"><div class="section-heading"><div><p class="eyebrow">SAVED ON THIS DEVICE</p><h1>My reveals.</h1></div><a class="button" href="/create/little-something">Make a surprise ↗</a></div><p>Up to 20 recent links are kept in this browser. Copy or export the links you want to keep. Clearing browser storage removes these saved copies.</p><p class="small">Removing a saved copy does not disable a link you have already sent.</p><div class="owner-list">${cards.map(r=>`<article class="owner-item"><div><span class="tier">Saved ${date(r.created)}</span><h2>${e(r.content.headline)}</h2><p>${e(catalogue.find(t=>t.id===r.content.templateId)?.name||'Your card')}</p></div><div class="owner-actions"><button data-share="${e(r.id)}">Link & QR</button><button data-edit-copy="${e(r.id)}">Edit a copy</button><button data-remove-copy="${e(r.id)}">Remove saved copy</button></div></article>`).join('')||'<div class="empty"><h2>Something lovely starts here.</h2><a class="primary button" href="/create/little-something">Make your first surprise ↗</a></div>'}</div>${cards.length?'<button id="export-links">Export saved links</button>':''}</section>`;document.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>showShare(cards.find(r=>r.id===b.dataset.share)));document.querySelectorAll('[data-edit-copy]').forEach(b=>b.onclick=()=>{const r=cards.find(r=>r.id===b.dataset.editCopy);try{localStorage.setItem(draftKey,JSON.stringify(r.content));location.href=routeUrl('/create/'+r.content.templateId);}catch{toast('Device storage is unavailable. Export your draft instead.');}});document.querySelectorAll('[data-remove-copy]').forEach(b=>b.onclick=()=>{showDialog('<h2>Remove this saved copy?</h2><p>Links you have already sent will still work.</p><button id="remove-copy">Remove saved copy</button>');dialog.querySelector('#remove-copy').onclick=()=>{try{localStorage.setItem('sr.web.reveals.v1',JSON.stringify(cards.filter(r=>r.id!==b.dataset.removeCopy)));dialog.close();owners();}catch{toast('This browser could not update your saved links.');}};});document.querySelector('#export-links')?.addEventListener('click',()=>download(JSON.stringify(cards,null,2),'surprise-links.json','application/json'));}

async function recipient(){const token=route.split('/')[2];main.innerHTML='<section class="recipient"><p class="recipient-intro">A little moment, just for you.</p><div id="recipient-experience"></div><label class="motion-control"><input id="recipient-reduce" type="checkbox"> Reduce motion</label><p class="recipient-note">No account needed. Take your time.</p><a class="small" href="/report">Something wrong? Report a problem</a></section>';try{const c=await api(`/api/r/${token}/cover`),t={id:c.templateId,mechanism:c.mechanism,occasions:['team-thank-you','client-appreciation'].includes(c.templateId)?['work']:[]};const mount=()=>{experience?.destroy();experience=mountExperience(document.querySelector('#recipient-experience'),t,c,()=>api(`/api/r/${token}/result`,{}),{loadClues:()=>api(`/api/r/${token}/clues`,{}),reduced:document.querySelector('#recipient-reduce').checked});};mount();document.querySelector('#recipient-reduce').onchange=mount;}catch(err){document.querySelector('#recipient-experience').innerHTML=`<div class="empty"><h1>This reveal is no longer available.</h1><p>Please ask the person who sent it.</p></div>`;}}

function information(){const pages={
 '/help':['A little help.','Pick a design, write your cover and final message, choose the look and opening style, then try Preview. Make a link and send the complete link to your recipient. Drafts and your most recent 20 links save in this browser; export a draft or your links to keep your own backup. Everyone can use a button to open their card. Images are made smaller on your device so they can travel with the link; large cards may not fit into a QR code. A recipient needs no account.'],
 '/privacy':['Your card travels with its link.','Your draft and saved links are stored in this browser using sr.web.draft.v1 and sr.web.reveals.v1. Card text and images are carried in the link fragment, which browsers do not send to the website server. The final message is encrypted in the link and opened on the recipient’s device; the key is also in that same link, so anyone holding the complete link can open it. This is not a private messaging service. Decorative background artwork is visible before opening. Images are resized and re-encoded on your device; the original file and its metadata are not included. The app adds no analytics or read receipts. GitHub Pages delivers the website and can receive ordinary request information such as your IP address. No account or payment is required.'],
 '/terms':['A little surprise, for now.','This is a free temporary edition of Surprise Reveal on Finger Game. It announces a gift; it does not supply tickets, reservations or presents. Use images and words you have permission to share. Share only content appropriate for your recipient. Links cannot be revoked or edited after sending, and continued hosting is not guaranteed. Send important practical arrangements separately.'],
 '/report':['Something wrong?','For a damaged link, ask the sender to copy the complete link again. Keep gift codes, passwords and sensitive details separate. The website does not send reports or collect recipient messages.']};const [title,text]=pages[route]||pages['/help'];main.innerHTML=`${devNotice()}<section class="prose"><p class="eyebrow">SURPRISE REVEAL</p><h1>${title}</h1><p>${e(text)}</p><a href="/">Back to the studio →</a><p><a href="/FingerOfShame/">Finger Game hub ↗</a></p></section>`;}


function download(text,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href);}
function missing(){main.innerHTML='<section class="empty"><h1>This page isn’t in the drawer.</h1><a href="/">Back to the studio</a></section>';}
function labContent(t){const c=sample(t);return new URLSearchParams(location.search).get('case')==='empty'?{...c,recipient:'',sender:'',note:'',number:''}:c;}
init();
